### ISSUE TITLE
Cura 4.1

### ISSUE THREAD

**Issue by h00etn** [trouch/CreawsomeMod#18]
Hello,

Cura 4.1 doesn't start when I put the resources folder in place and rename the original one. This is the error traceback info:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/site-packages/cx_Freeze/initscripts/__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/site-packages/cx_Freeze/initscripts/Console.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Users/ultimaker/build/4.1/build/inst/bin/cura_app.py", line 136, in <module>
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/cura/CuraApplication.py", line 771, in run
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/cura/UI/WelcomePagesModel.py", line 211, in initialize
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/cura/UI/WelcomePagesModel.py", line 235, in _initialize
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/cura/UI/WelcomePagesModel.py", line 202, in _getBuiltinWelcomePagePath
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/Resources.py", line 85, in getPath
FileNotFoundError: Could not find resource ('WelcomePages/WelcomeContent.qml',) in 129

**Comment by Ne0tuX** [comment]
The solution is shown on the last line of your log: copy the folder "WelcomePages" from yor backup folder to "C:\Program Files\Ultimaker Cura 4.1\resources\qml". I just tested, works fine.

**Comment by trouch** [comment]
The mod is just not compatible with Cura 4.1 yet.
I actually need a mod version per cura release !

**Comment by niemyjski** [comment]
does beta3 support Cura 4.1?

**Comment by ptyork** [comment]
> 
> 
> does beta3 support Cura 4.1?

No.

**Comment by Revolt64** [comment]
Why are you closing these issues before they are resolved?

I greatly appreciate your work, but you shouldn't be closing issues until they're resolved, as it's a good place to track for users so we know when the issue in question is resolved.

Thanks for all your great work on the mod!
