### ISSUE TITLE
Mac not working

### ISSUE THREAD

**Issue by maxfarnell** [trouch/CreawsomeMod#38]
I did everything it said, I renamed the file "resources_old" and copy and pasted the new one in. Rebooted Cura and no change what so ever. What am I doing wrong???
<img width="324" alt="Screenshot 2019-05-27 at 22 13 41" src="https://user-images.githubusercontent.com/48635474/58439689-4f623d00-80cd-11e9-8ba2-e23a55c96b64.png">
<img width="588" alt="Screenshot 2019-05-27 at 22 13 35" src="https://user-images.githubusercontent.com/48635474/58439690-4f623d00-80cd-11e9-9336-e852b6f8c3d4.png">
<img width="587" alt="Screenshot 2019-05-27 at 22 13" src="https://user-images.githubusercontent.com/48635474/58439691-4ffad380-80cd-11e9-8914-49dbecd4d1fc.png">

**Comment by eptak** [comment]
I've just updated another mac at home without any issue !

**Comment by maxfarnell** [comment]
Am i missing something or doing something wrong?

**Comment by trouch** [comment]
having crash log or screenshot would be helpful

**Comment by safetyABJ** [comment]
I'm having the same issue, clean install of Cura with new Creawsome mod installed crashes on startup: Cura 4.1.0, OS X 10.12.6

Error Traceback

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/site-packages/cx_Freeze/initscripts/__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/site-packages/cx_Freeze/initscripts/Console.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Users/ultimaker/build/4.1/build/inst/bin/cura_app.py", line 136, in <module>
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/cura/CuraApplication.py", line 771, in run
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/cura/UI/WelcomePagesModel.py", line 211, in initialize
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/cura/UI/WelcomePagesModel.py", line 235, in _initialize
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/cura/UI/WelcomePagesModel.py", line 202, in _getBuiltinWelcomePagePath
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/Resources.py", line 85, in getPath
FileNotFoundError: Could not find resource ('WelcomePages/WelcomeContent.qml',) in 129

Logs

Thread 0x0000700012695000 (most recent call first):
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/selectors.py", line 376 in select
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/subprocess.py", line 1715 in _communicate
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/subprocess.py", line 1072 in communicate
  File "/Applications/Ultimaker Cura.app/Contents/MacOS/plugins/plugins/RemovableDriveOutputDevice/OSXRemovableDrivePlugin.py", line 17 in checkRemovableDrives
  File "/Applications/Ultimaker Cura.app/Contents/MacOS/plugins/plugins/RemovableDriveOutputDevice/RemovableDrivePlugin.py", line 59 in _updateThread
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 862 in run
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x0000700012192000 (most recent call first):
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 297 in wait
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/site-packages/zeroconf.py", line 1569 in wait
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/site-packages/zeroconf.py", line 1153 in run
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x0000700011c8f000 (most recent call first):
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 297 in wait
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/site-packages/zeroconf.py", line 1569 in wait
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/site-packages/zeroconf.py", line 1017 in run
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x000070001178c000 (most recent call first):
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/site-packages/zeroconf.py", line 946 in run
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x0000700011289000 (most recent call first):
  File "/Applications/Ultimaker Cura.app/Contents/MacOS/plugins/plugins/USBPrinting/USBPrinterOutputDeviceManager.py", line 76 in _updateThread
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 862 in run
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x0000700010d86000 (most recent call first):
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/Backend/Backend.py", line 150 in _storeStderrToLogThread
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 862 in run
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x0000700010883000 (most recent call first):
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/Backend/Backend.py", line 138 in _storeOutputToLogThread
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 862 in run
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x0000700010380000 (most recent call first):
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 297 in wait
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 549 in wait
  File "/Applications/Ultimaker Cura.app/Contents/MacOS/plugins/plugins/UM3NetworkPrinting/src/UM3OutputDevicePlugin.py", line 442 in _handleOnServiceChangedRequests
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 862 in run
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x000070000fd77000 (most recent call first):
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 293 in wait
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x000070000f874000 (most recent call first):
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 293 in wait
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x000070000f371000 (most recent call first):
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 293 in wait
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x000070000ee6e000 (most recent call first):
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 293 in wait
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x000070000e96b000 (most recent call first):
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 293 in wait
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x000070000e468000 (most recent call first):
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 293 in wait
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x000070000df65000 (most recent call first):
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 293 in wait
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x000070000da62000 (most recent call first):
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 293 in wait
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/Users/ultimaker/build/env/4.1/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Current thread 0x00007fff9e4473c0 (most recent call first):
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/cura/CrashHandler.py", line 306 in _logInfoWidget
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/cura/CrashHandler.py", line 156 in _createDialog
  File "/Users/ultimaker/build/4.1/build/inst/lib/python3.5/site-packages/cura/CrashHandler.py", line 77 in __init__
  File "/Users/ultimaker/build/4.1/build/inst/bin/cura_app.py", line 102 in exceptHook

**Comment by Roiberko** [comment]
Fix is easy, just copy from the backupdir/qml the directory "WelcomePages" to new resources directory

**Comment by trouch** [comment]
4.1 is not supported yet
