### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by yochillum** [trouch/CreawsomeMod#4]
When trying to run after loading resources folder, a long string of crash reports populate, but I am unable to read them. They seem to multiply until the program closes prematurely.

**Comment by yochillum** [comment]
UPDATE: Was able to finally catch the error traceback:
Traceback (most recent call last):
  File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\Qt\Bindings\MainWindow.py", line 218, in _render
  File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\Qt\QtRenderer.py", line 120, in beginRendering
  File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\Qt\QtRenderer.py", line 185, in _initialize
  File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\View\GL\OpenGL.py", line 45, in __init__
RuntimeError: Try to create singleton 'OpenGL' more than once

**Comment by yochillum** [comment]
Sorry to clutter comments: Identified missing shaders in the shaders folder. Placed missing ones from resources backup folder, and launches successfully.
